---
title: "Cleaning datasets"
author: "Angela Wei, Brooke Bodine, Rosa Ferdelman"
date: "2025-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(readxl)
library(readr)
library(janitor)
```

# Import datasets

```{r}
# Healthcare access dataset
excel_sheets("2025 County Health Rankings Ohio Data - v3.xlsx")

main <- read_excel("data/2025 County Health Rankings Ohio Data - v3.xlsx",
                       sheet = "Select Measure Data", skip = 1)

# SVI Dataset 
county_raw = read_csv("SVI_County_Export.csv", show_col_types = FALSE) |>
  clean_names()

#now we can clean them properly
county_svi = county_raw |>
  separate(location, into = c("county_name", "state"), sep = ", ") |>
  mutate(
    county = county_name |> 
      str_remove(" County") |>
      str_to_upper()
  )

#and prepare categories/factors
prep = function(df) {
  df |>
    mutate(across(where(is.character), as.factor)) |>
    mutate(across(where(is.factor), ~fct_explicit_na(.x, na_level = "Missing"))) |>
    mutate(across(where(is.numeric), ~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x)))
}

county_svi_simple = prep(county_svi)
county_svi_simple$county_name <- gsub(" County$", "", county_svi_simple$county_name)
county_svi_simple$fips <- sprintf("%05d", county_svi_simple$fips)


head(county_svi_simple)
print(colnames(county_svi_simple))

```

