---
title: "pubhlth project"
author: "Angela Wei, Brooke Bodine, Rosa Ferdelman"
date: "2025-11-16"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readxl)
library(readr)
library(janitor)
library(corrplot)
library(car)
library(MASS)
library(ggrepel)
```

## R Markdown

### Import datasets
```{r cars}
# SVI Dataset 
county_raw = read_csv("../data/SVI_County_Export.csv", show_col_types = FALSE) |>
  clean_names()

# SVI dataset cleaning
county_svi = county_raw |>
  separate(location, into = c("county_name", "state"), sep = ", ") |>
  mutate(
    county = county_name |> 
      str_remove(" County") |>
      str_to_upper()
  )
prep = function(df) {
  df |>
    mutate(across(where(is.character), as.factor)) |>
    mutate(across(where(is.factor), ~fct_explicit_na(.x, na_level = "Missing"))) |>
    mutate(across(where(is.numeric), ~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x)))
}

county_svi_simple = prep(county_svi)
county_svi_simple$county_name <- gsub(" County$", "", county_svi_simple$county_name)
county_svi_simple$fips <- sprintf("%05d", county_svi_simple$fips)
head(county_svi_simple)

```

### Create & Export Healthcare Access Dataset 

```{r}
# Healthcare access dataset
excel_sheets("../data/2025 County Health Rankings Ohio Data - v3.xlsx")
main <- read_excel("../data/2025 County Health Rankings Ohio Data - v3.xlsx",
                       sheet = "Select Measure Data", skip = 1)
healthcare_vars <- c(
  "FIPS", "State", "County",  # keep these for identification

  "# Primary Care Physicians",
  "Primary Care Physicians Rate",
  "Primary Care Physicians Ratio",
  "National Z-Score...90"
)

healthcare_access_data <- main[, healthcare_vars]
healthcare_access_data <- healthcare_access_data[-1, ]
head(healthcare_access_data)

```

### Join into single dataset

```{r}
#inner join the two datasets by county, wsanity checked 54 colns
merged_data = healthcare_access_data %>% 
  left_join(county_svi_simple, by = c("FIPS" = "fips"))

head(merged_data)
print(colnames(merged_data))

# Correlation matrix for merged dataset
numeric_vars <- dplyr::select(merged_data, where(is.numeric))
cor_matrix = cor(numeric_vars, use = "pairwise.complete.obs")
corrplot(cor_matrix, method = "color", tl.cex = 0.7)
```

### Fit model

```{r}
full_mod = lm(
  `Primary Care Physicians Rate` ~ 
    total_population +
    housing_units +
    occupied_households +
    socioeconomic_score +
    below_poverty +
    unemployed +
    income +
    no_hs_diploma +
    house_composition_disability_score +
    age_65_or_older +
    age_17_or_under +
    civilian_with_a_disability +
    single_parent_household +
    minority_status_language +
    minority +
    speak_english_less_than_well +
    housing_type_transportation+
    multi_unit_structure +
    mobile_homes +
    crowding +
    no_vehicle +
    group_quarters,
  data = merged_data
)
summary(full_mod)
```

```{r}
# Visualizations

# Residuals plots
par(mfrow = c(2,2))
plot(full_mod)

# PCP Prediction plot
merged_data$pred_full <- predict(full_mod)

ggplot(merged_data,
       aes(x = pred_full, y = `Primary Care Physicians Rate`)) +
  geom_point(alpha = 0.7, color = "darkred") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(
    title = "Predicted vs Actual Primary Care Physician Rate (Full Model)",
    x = "Predicted",
    y = "Actual"
  ) +
  theme_minimal()

# PCP vs SVI score
ggplot(merged_data, aes(x = x2018_overall_svi_score, y = `Primary Care Physicians Rate`)) +
  geom_point(alpha = 0.6, color = "steelblue") +
  geom_smooth(method = "lm", se = TRUE, color = "darkred") +
  geom_text_repel(data = subset(merged_data, `Primary Care Physicians Rate` > quantile(`Primary Care Physicians Rate`, 0.95)),
                  aes(label = county_name), size = 3, color = "black") +
  labs(
    title = "Primary Care Physician Rate vs Social Vulnerability Index",
    x = "Social Vulnerability Index (SVI)",
    y = "Primary Care Physicians Rate"
  ) +
  theme_minimal()

```

### Model Selection

```{r}
#vif(full_mod)
step_mod = stepAIC(full_mod, direction = "backward")
```


```{r}
AIC(full_mod, step_mod)
BIC(full_mod, step_mod)
summary(full_mod)$adj.r.squared
summary(step_mod)$adj.r.squared
names(step_mod$coefficients)[-1]
```
```{r}
summary(step_mod)
```

